Prevent grab input from triggering attack/shield on ground
HDR-Development/HewDraw-Remix pull request #1012
Opened 2022-09-11 02:12 UTC by jobrien97

- Grab inputs can no longer cause an attack or shield on the ground
   - If grab button is held past the tap buffer window however, shield will still come out

Resolves #1011

2022-09-11 03:14 UTC, WuBoytH requested changes, later dismissed
This will not be enough to prevent Grab from triggering these actions, especially in the case of Shielding, where the only check is whether or not the guard button is pressed, ignoring all CAT flags.

2022-09-11 03:15 UTC, jobrien97 commented
> This will not be enough to prevent Grab from triggering these actions, especially in the case of Shielding, where the only check is whether or not the guard button is pressed, ignoring all CAT flags.

uhhh I exit the shield transition func if Catch cmd cat is active, so that shouldn't matter (?)

2022-09-11 03:21 UTC, WuBoytH commented
> > This will not be enough to prevent Grab from triggering these actions, especially in the case of Shielding, where the only check is whether or not the guard button is pressed, ignoring all CAT flags.
> 
> uhhh I exit the shield transition func if Catch cmd cat is active, so that shouldn't matter (?)

You'll love this
holding Grab counts as holding Shield, doesn't matter if the cat flag is active

2022-09-13 04:09 UTC, WuBoytH approved these changes
Gameing

2022-09-13 17:57 UTC, merged