Falco laser adjustments
HDR-Development/HewDraw-Remix pull request #1021
Opened 2022-09-13 02:18 UTC by Riah321

Now that ASDI has been implemented we can make laser a real move again! Added damage falloff similar to P+ to de-incentivize laser camping while properly rewarding close range play.

2022-09-13 03:08 UTC, TeamPearson commented
Yet to play on this but I don't think that laser has had enough time to be hashed out with asdi being merged. My thinking is that asdi being weaker than melee and laser having 1:1 melee values makes this a non necessary change.

2022-09-13 03:45 UTC, TeamPearson requested changes
3.0 damage lasers are doing what you want.
2.0 damage lasers are doing what you want.
1.5 lasers need a kbg value of 75 to have 1 less frame of stun to achieve your goal.

2022-09-13 04:58 UTC, yoonikoo commented
The changes feel really solid. The further away the opponent is, less hitstun is applied to them from laser. This discourages laser camping as the close laser makes the move committal and rewards aggressive play. This is a middle ground for those that wanted laser nerfed and those that thought that laser was too weak in the current state of the game with the global engine changes.

2022-09-13 07:08 UTC, Kaiokendo661 commented
Extremely cash money changes 🗿

2022-09-13 15:13 UTC, TeamPearson submitted a review, later dismissed
If your labbing was correct and that frame data checks out then it lgtm. Not sure why lasers need drop off stun when their utility is net worse than melee and p+ though.

2022-09-13 15:36 UTC, Riah321 commented
Once the code matches the desired numbers it'll be 1-1. Him not having F1 shine really hurts his defense though so maybe close laser should be 13F? not really sure what to do since that would be extremely degenerate.

2022-09-17 07:33 UTC, Riah321 commented
PR is tested and finished. Finally.

2022-09-17 07:38 UTC, Riah321 commented
PR is tested and complete. Finally.

2022-09-24 00:26 UTC, Riah321 commented
I've gotten my dev environment fixed, tested on all kinds of weights and it finally, actually does what it says on the tin.

2022-09-25 14:43 UTC, jobrien97 requested changes

2022-09-25 14:43 UTC, jobrien97 commented on fighters/falco/src/acmd/other.rs
> +    frame(lua_state, 3.0); {
This looks mistakenly edited

2022-10-07 21:58 UTC, TeamPearson approved these changes, later dismissed
lgtm

2022-10-07 22:02 UTC, TeamPearson commented on fighters/falco/src/acmd/other.rs
> +    frame(lua_state, 3.0); {
This appears fixed in the file

2022-10-07 22:06 UTC, jobrien97 submitted a review, later dismissed

2022-10-10 01:37 UTC, TeamPearson submitted a review, later dismissed

2022-10-10 02:58 UTC, TeamPearson approved these changes

2022-10-10 16:56 UTC, merged