Knockback adjustments
HDR-Development/HewDraw-Remix pull request #1030
Opened 2022-09-17 03:18 UTC by jobrien97

- When hit from behind, you will now *always* turn around to face the attacker, rather than flying facing away from them at mid-high %s
- Reverted vanilla's slowing down of DamageFly, DamageFlyTop, and DamageFlyMeteor knockback animations to make knockback feel more natural, akin to Melee/PM
- Knockback angle range to trigger DamageFlyTop animation reduced 0.785398-2.35619 -> 1.22173-1.91986 (radians)
- Knockback smoke GFX shrunk by 25%
- Missed tech GFX made smaller & more transparent

https://user-images.githubusercontent.com/47401664/190838559-dafe5641-86cc-4895-9e32-cfe366d420c7.mp4

Resolves #879

2022-09-17 03:23 UTC, Riah321 commented
I love you

2022-09-17 03:30 UTC, WuBoytH approved these changes

2022-09-17 03:31 UTC, WuBoytH requested changes

2022-09-17 03:31 UTC, WuBoytH commented on fighters/common/src/function_hooks/effect.rs
> +    if SHOCKWAVE_FX.contains(&effHash.hash) {
wait this should be lowercase lmao

2022-09-17 04:08 UTC, WuBoytH submitted a review, later dismissed
Or y'know you can just do the opposite of what I said lmao

2022-09-18 05:39 UTC, yoonikoo commented
The chunkiness of the knockback and the emphasis on smoke is now fixed! It looks good to play on! LGTM

2022-09-18 06:00 UTC, Riah321 commented
I played on the first version and it was amazing. can't wait to try the current iteration!

2022-09-18 19:59 UTC, WuBoytH approved these changes

2022-09-19 20:10 UTC, merged