Isabelle Tweaks
HDR-Development/HewDraw-Remix pull request #1062
Opened 2022-10-01 15:29 UTC by elias-michaias

IN PROGRESS (Don't review this yet)

2022-10-04 05:56 UTC, yoonikoo commented
Isabelle now has sauce. Has really cool combo routes with the new Up B changes and the new FAIR. Also, with the new jump squat, she is able to do these combos with better, but tighter execution. If there is one thing, the range on FAIR is a bit way too small.

2022-10-05 23:47 UTC, elias-michaias commented
Adjusted fair hitbox size, still working on SFX choice.

2022-10-06 04:33 UTC, yoonikoo commented
Tested out the new changes. LGTM. Still waiting for more changes such as fishrod nerfs and new SFX.

2022-10-07 16:57 UTC, elias-michaias commented
> Tested out the new changes. LGTM. Still waiting for more changes such as fishrod nerfs and new SFX.

Fixed both of these, and a lot more.

2022-10-08 02:56 UTC, Kaiokendo661 commented
Good shit for giving her some well needed adjustments while still leaving her viable yall did great 👌

2022-10-18 16:50 UTC, WuBoytH requested changes, later dismissed

2022-10-18 16:50 UTC, WuBoytH commented on fighters/shizue/src/acmd/aerials.rs
> +    frame(lua_state, 9.0);
Please generate the effect a frame or two earlier than the hitbox so the animation matches with the end of the attack arc.

2022-10-31 22:49 UTC, hdr-balance-backroom commented
APPROVED

2022-11-01 02:53 UTC, MadVillainLordQ approved these changes
LGTM

2022-11-01 02:54 UTC, merged