ECB overhaul
HDR-Development/HewDraw-Remix pull request #1157
Opened 2022-10-25 19:54 UTC by jobrien97

**ECB shifts now behave identically to Melee:**
- For the first 9 frames of being airborne, your ECB's bottom point will be locked to your Top bone (your base position).
- On frame 10 and onwards, your ECB's bottom point will use its regular ECB pattern, meaning it will be calculated identically to the other 3 points.

Previously, we had used a hard "ECB shift amount" constant, defined per character, to shift your ECB upwards.
Now, we allow the game to calculate the bottom ECB point identically to the other 3 points, which means its location can vary significantly depending on how an animation contorts your character's body in the air.

Marth's double jump (old):

https://user-images.githubusercontent.com/47401664/197868717-f85ab207-c21c-4527-aa69-3b6108591641.mp4

Marth's double jump (new):

https://user-images.githubusercontent.com/47401664/197868741-e63a5018-5720-4ec1-9b93-c593b91c2449.mp4

 ---
The previous implementation shifted your *entire* ECB upwards, rather than just the bottom ECB point. This caused your character's head collision to be raised as well, which may have caused some weird ceiling interactions.
Now, your ECB is "squished" upwards from the bottom point, to around your character's knees, with the top point remaining tied to your head.

Frame 12 of Marth's jump (old):

![ecb_old](https://user-images.githubusercontent.com/47401664/197868776-ad4f5a0d-9db5-490e-925c-b5286fc11b4f.jpg)

Frame 12 of Marth's jump (new):

![ecb_new](https://user-images.githubusercontent.com/47401664/197868821-d85020b8-eb04-432c-bf55-ab35c906bc94.jpg)

 ---
The new implementation also allows for the return of **No-Impact Lands (NILs)**:
- Due to how the game handles collision, it perceives "moving downwards" as any time your current frame's ECB bottom is lower than the previous frame's ECB bottom. The game only allows you to land when "moving downwards."
- A character's aerial animation may contort their body in such a way that their ECB's bottom stretches downward for a frame or two. During this time, the game perceives you as "moving downwards," **even if you are moving upwards**. This means the game allows you to land.
- Thus, if you are just above a surface when your ECB stretches downwards, *even if moving upwards*, you will land with your character's normal landing lag (2-5 frames depending on the character).

Here is one (frame-perfect) example in action:

https://user-images.githubusercontent.com/47401664/197866360-5d2d0835-f456-4a36-9259-87ef525514f7.mp4

This also fixes platform canceling aerial attacks.

Resolves #1146 
Fixes #1158

2022-10-25 21:29 UTC, yoonikoo commented
Platform cancelling indeed is back. Tested it on Marth, Falco, Joker. There seems to be no ECB issues relating to Ridley or Yoshi anymore with this PR. LGTM.

2022-10-31 22:39 UTC, WuBoytH submitted a review, later dismissed

2022-10-31 22:56 UTC, blu-dev requested changes

2022-10-31 22:56 UTC, blu-dev commented on dynamic/src/consts.rs
> +            pub const DISABLE_ECB_SHIFT: i32 = 0x1111;
no

2022-10-31 22:56 UTC, blu-dev commented on fighters/common/src/function_hooks/collision.rs
> +#[skyline::hook(offset = 0x48fc40)]
I don't like this, for a number of reasons:

Any point *ever* we call this function with `trans`, it's going to return invalid data and that's not really going to be documented anywhere.

That being said, I would appreciate if this was handled via a VarModule flag to wrapped around the `call_original!` in the above hook. I don't want to be chasing a bug 10 months from now related to this. It's the simplest solution, something like:
```rs
VarModule::on_flag((*boma).object(), vars::instance::IS_GETTING_POSITION_FOR_ECB);
call_original!(...);
VarModule::off_flag((*boma).object(), vars::instance::IS_GETTING_POSITION_FOR_ECB);
```
and then check the flag in this hook.

2022-11-01 19:21 UTC, techyCoder81 approved these changes
The changes made seem to meet the requests in previous review. lgtm.

2022-11-01 19:39 UTC, merged