Yoshi Adjustments
HDR-Development/HewDraw-Remix pull request #1235
Opened 2022-12-02 22:02 UTC by MadVillainLordQ

Yoshi has received quite a bit of angle adjustments and damage adjustments across his toolkit. Along with that, both egg toss and end egg roll have had some functionality changes that reduce their potency overall. Egg roll and egg toss will most likely need further refinements in the future.

Notes:
- Egg roll is no longer jump cancellable or air dodge cancellable. Instead, the ending animation has been sped up significantly to still allow for follow ups on hit
- Egg toss has had its minimum angle increased and has a much more parabolic arc with the lowest toss. This goes along with a reduction in vertical height gained by the initial egg toss and subsequent egg tosses.
- Bair has a much more different feel to it as it leans more into its melee counterpart with slower but longer lasting hitboxes.

[Old vs. New Hitbox Comparison](https://imgur.com/a/wvdvj7U)
[Yoshi PR Changelog.txt](https://github.com/HDR-Development/HewDraw-Remix/files/10144676/Yoshi.PR.Changelog.txt)

2022-12-04 23:52 UTC, hdr-balance-backroom commented
APPROVED

2022-12-05 00:03 UTC, techyCoder81 approved these changes, later dismissed

2022-12-12 20:38 UTC, SkewedAskew requested changes, later dismissed
Bair needs less frame advantage (currently +8/+24 at 0/100%)

2022-12-14 01:47 UTC, jobrien97 approved these changes

2022-12-14 06:24 UTC, merged