Bayonetta Mini-Rework
HDR-Development/HewDraw-Remix pull request #1331
Opened 2023-01-22 07:49 UTC by jaccob101

Detronlegacy and I have collabed on Bayonetta changes with feedback from other players in the Bayonetta channel. Changelist to be updated: https://docs.google.com/document/d/1T2qfDRQdxeL_X-TunFrLUyK2y9YozlhEIoo2xSFHirg/edit

Requires this motion list and animation to be dropped in hdr-assets to function properly 
[drag onto hdr-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/10473949/drag.onto.hdr-assets.zip)

The goal was to make her less focused on witch twist and sdi-ing. Changes are open to feedback but I believe they improve her game-feel.

2023-01-23 00:06 UTC, hdr-balance-backroom commented
Witch Time:
- Revert animation changes, use motion rating for the relevant scripts instead
- Increase animation duration from what it currently is, as the move is very spammable

2023-01-23 02:15 UTC, jaccob101 commented
I tried using fsms to change the frame data of witch time but it broke the baked movement and made the move not function. I changed the FAF from 33 to 39, so 24 frames of lag after the witch time window ends.

2023-01-23 02:26 UTC, jaccob101 commented
If you have a suggestion on how to use FSMs without having to change the animation in the first place to remove the movement then I can try it

2023-01-27 16:03 UTC, WuBoytH commented on romfs/source/fighter/bayonetta/param/vl.prcxml
> +		  <int hash="0x0d76ae442e">3</int>
I would suggest not using `tab` to space out lines in the prcxml, use spaces instead

2023-02-01 16:30 UTC, jaccob101 commented
After trying it disabling move true on the witch time just makes it teleport back after moving during the animation so I would need more guidance if the aenimation needs to be the vanilla one

2023-02-08 00:45 UTC, hdr-balance-backroom commented
This will be reviewed further after the next beta release

2023-02-26 01:06 UTC, hdr-balance-backroom commented
Please put a code freeze on this (no more commits) until we can properly evaluate

2023-02-27 02:55 UTC, jaccob101 commented
Ok i'll abstain but i have a commit ready if you want me to remove the jabs and ftilt 3 extra hitstun and stuff

2023-03-13 04:36 UTC, hdr-balance-backroom requested changes
- Remove .vs files from PR
- Revert jumpsquat to 5 frames
  - this change was made to offset the potency of characters with especially strong aerial tools
- Revert model scale increase
- Lower knockback on jab2 to reduce frame advantage (currently +13/+9 at 0% for the inner/outer hitboxes)
- Remove additional hitstun on ftilt1 if it is not absolutely necessary to combo into ftilt2/3
- Revert utilt and dtilt startup decreases
  - Bayonetta should have below average neutral tools to offset her punish game
- Change nair hitlag to 1.0 on all hits
- Remove held nair additional hitstun and change hitlag/SDI to 1.0
- Revert fair landing lag to 9 frames
- Revert bair landing lag to 10 frames and change the front leg and hip hitboxes to reverse hit
- Remove additional hitstun on held uair
- Remove dair shieldstun multiplier and change hitboxes to reverse hit
- Change Heel Slide to send into fall instead of tumble when sliding off an edge (may have to edit the status script)
- Reduce bullet art ABK hitbox size, move to only cover lower leg/hip area
- Revert DABK hitbox size
  - this move should be intentionally negatively disjointed
- Potentially remove the directional input for dabk in favor of the new attack+special input
- Standardize Witch Time startup to frame 5 for both ground and air
- Reduce fthrow voice line chance to around 10-20%

2023-03-16 17:30 UTC, jaccob101 commented
I've been playing more with the requested changes and I just would like to ask if the uptilt startup and the jump squat are non-negotiable? I nerfed up tilt's lingering hitboxes by 33% and previously compensated the FAF so that it wouldn't be spammable in neutral. If not 8 frames of startup 9 frames would be enough to improve the feel. Also, the majority of her aerial options are nerfed and most of her rising aerials don't hit grounded opponents. None of her aerial options are safe on shield and now she gets punished harder for mistakes due to her higher gravity/fall speed. I believe the start-up change would not improve her neutral much, just making it feel better to move with her and wavedash. She already will generally use witch twist out of shield because it's the only one that can consistently hit low opponents while also being far faster than her next fastest oos (10 frames). Also I agree with the rest of your feedback as many of those changes were unnecessary and should have been reverted after testing. The landing lag changes were an attempt to make her moves safer on shield as back air is far more committal now for less reward, especially after the jump revert. The fair change did improve the combo potential of landing fair 3 so I understand that 2 frames off might be more impactful than intended. The dabk size change was partially to make the combo potential worse as it made her get sent farther away from the opponent, but after testing it versus better players than me DI and ASDI suffice. I don't want to remove her other dabk inputs so it doesn't alienate bayo mains that have muscle memory. Thank you for looking at this pr and apologies for not realizing I should have not put an unfinished pr on here, just wanted people to be able to download it from the launcher.

2023-03-16 18:59 UTC, hdr-balance-backroom commented
> If not 8 frames of startup 9 frames would be enough to improve the feel. None of her aerial options are safe on shield and now she gets punished harder for mistakes due to her higher gravity/fall speed. I believe the start-up change would not improve her neutral much, just making it feel better to move with her and wavedash

Again, the point is that her neutral tools should be intentionally worse than average because her punish game is well above average. Jumpsquat also plays into this, she can get full combos off stray hits easier than other characters with jump/aerial/special cancels. This rework already changes so much, the current implementation need to sit a while before making any more changes. If utilt ends up being lackluster then it can be reevaluated at a later point

2023-03-29 20:26 UTC, jaccob101 commented
Ok I fixed every bug I could find, cleaned up effects to match shortened distances and smaller hitboxes, and normalized the jab hitstun values. It should have a lot of the bs ironed out so I feel it's ready for a retest

2023-04-07 23:53 UTC, jaccob101 commented
> Witch Time:
> 
>     * Revert animation changes, use motion rating for the relevant scripts instead
> 
>     * Increase animation duration from what it currently is, as the move is very spammable

---
Late but figured out I needed to set the FSM as a float/float instead of an int/int to make this work. Animations have been removed from the folder, but it still needs a motion list edit.

2023-04-08 15:59 UTC, MadVillainLordQ commented on fighters/bayonetta/src/acmd/aerials.rs
> +        ATTACK(fighter, 1, 0, Hash40::new("kneel"), 12.0, 40, 121, 0, 15, 4.7, 6.7, 0.0, 0.0, None, None, None, 1.2, 1.0, *ATTACK_SETOFF_KIND_ON, *ATTACK_LR_CHECK_POS, false, 0, 0.0, 0, false, false,
Hitlag Modifier should be 1.0

2023-04-30 20:23 UTC, hdr-balance-backroom commented
Requesting a full code freeze. Please do not make any more commits, including merging in dev

2023-04-30 20:49 UTC, jaccob101 commented
just saw will do

2023-06-07 00:05 UTC, hdr-balance-backroom requested changes, later dismissed
- Reduce Bayonetta's ability to gain back two resources when sent into tumble to just one resource
- Increase the SDI multiplier on held uair hitboxes from 1.0x -> 1.5x
- Decrease on hit frame advantage of held nair hitboxes (currently sits at +8/+14 at 0/100). Suggested amount is from +5-+6 at 0% and +11-+12 at 100%
- Upwards ABK gives Bayonetta less gravity on hit than on whiff
- Remove ABK's ability to cancel 5 frames sooner when hitting a shield

2023-06-07 05:02 UTC, jaccob101 commented
> 

Done I believe. 
Held N-Air: BKB from 35 to 30 (should lower adv by 2 frames)
Held U-Air: Sdi from 1x to 1.5x
Resources recovered standardized, hit flag no longer checks for shield-hits
I believe the U-Abk losing height on hit was the result of a bug where I improperly checked for the hit-flag, making it so it would transition into fall kinetic kind where normally the move would have been cancelled already (unless you meant the opposite)

2023-06-11 02:39 UTC, SkewedAskew approved these changes
'Twas a long journey, good job

2023-06-11 02:39 UTC, merged