Piranha Plant Rework (Redux): Adaptive Roots
HDR-Development/HewDraw-Remix pull request #1379
Opened 2023-02-12 02:26 UTC by h3ra-ai2020

This rework aims to turn Piranha Plant into a stance character with a new shield special, Adaptive Roots. The standard plant has the best movement, the putrid plant is the most defensive with attacks capable of poisoning the foe, and the prickly plant packs the biggest punch with heavy, yet slow attacks.

### Entering Stances
- While in shield, press a taunt button to change stance. Up taunt changes to Putrid Plant, down taunt changes to Prickly Plant, and side taunt changes to the standard plant.
### General Stance Changes
- Plant mves slower when Putrid/Prickly
- Putrid's attacks deal less damage, and bites deal poison DoT
- Prickly's attacks are slowed down, but deal more damage, head attacks most of all
### Ptooie
- Putrid Ptooie deals poison DoT
- Prickly Ptooie is larger and deals more damage, but goes a shorter distance
### Poison Breath → Adaptive Breath
Poison Cloud has been changed into a completely new move, Adaptive Breath- a close-range spit that has different properties depending on Plant's current stance!
- Standard Plant spits a gust of wind that sends at a nasty angle
- Putrid Plant spits a multihit poison breath that poisons
- Prickly Plant bites instead of spitting, dealing high shield damage and piercing shields at full charge
### Piranhacopter (These changes are planned for the recovery sweep, so they will be moved from this PR in time
- Is now a single hit
- Grounded version no longer leaves the ground
- Cancel goes into special fall immediately
- Aerial version moves much slower
Changelog, hitbox diffs, and dev forum under construction
### In Progress changes
- Differentiating up b and down b between stances
- stance switch currently does not change motion into an animation

2023-02-27 20:33 UTC, Detronlegacy commented
Wavedashes allow plant to ignore speed reductions caused by stance switching.

2023-03-01 16:30 UTC, WoodrowManuel commented
Putrid Ptooie's initial hitbox was moved from the lips to the base of the pot.
https://streamable.com/5cnggo

2023-03-16 17:50 UTC, jobrien97 requested changes, later dismissed

2023-03-16 17:50 UTC, jobrien97 commented on fighters/packun/src/opff.rs
> +            KineticModule::add_speed_outside(fighter.boma(), *KINETIC_OUTSIDE_ENERGY_TYPE_WIND_NO_ADDITION, &motion_vec);
Please don't use wind, dash should already be covered in the control energy status speed mul, no?

2023-03-16 17:50 UTC, jobrien97 commented on fighters/packun/src/opff.rs
> +    lua_bind::FighterKineticEnergyMotion::set_speed_mul(fighter.get_motion_energy(), mul);
Please do
`
fighter.clear_lua_stack();
lua_args!(fighter, FIGHTER_KINETIC_ENERGY_ID_MOTION);
let og_speed_mul = app::sv_kinetic_energy::get_speed_mul(fighter.lua_state_agent);
lua_bind::FighterKineticEnergyMotion::set_speed_mul(fighter.get_motion_energy(), og_speed_mul * mul);
`
instead. This allows dash attack to be naturally affected by your status speed mul.

2023-03-16 17:50 UTC, jobrien97 commented on fighters/packun/src/acmd/ground.rs
> +    sv_kinetic_energy!(set_speed_mul, fighter, FIGHTER_KINETIC_ENERGY_ID_MOTION, stance.da_speed);
Please revert this in favor of what I commented in opff.rs

2023-05-30 18:58 UTC, SkewedAskew approved these changes

2023-05-30 19:08 UTC, merged