Corrin recovery adjustments
HDR-Development/HewDraw-Remix pull request #1408
Opened 2023-02-23 22:59 UTC by yoonikoo

Corrin Up B was a little too disjointed. This tones it down.

<==CORRIN==>
SPECIALS
-Up B (Initial Hitboxes)
~[R] Hitlag reduced from 1.5 to 1.0
~[R] FKB changed from 160 to 150
~[R] Removed id1 hitboxes

-Up B (Multihit Hitboxes)
~[R] Hitlag reduced from 0.7 to 0.5 on multi-hit hitboxes
~[R] FKB changed on all hitboxes (id0: 150-->140, id1: 150-->140, id2: 150 -->140, id3: 165-->155, id4: 165-->150)
~[R] id1 and id2 hitbox y-offset changed from 5.5 to 4.0

-Up B (Launcher Hitboxes)
~[R] Hit lag reduced from 2.1 to 1.5 on launcher hitboxes
~[R] Added 2 more hitboxes on the outer part of the wings
~[-] Inner launcher hitbox sizes decreased from 8.5 to 4.0
~[R] Outer launcher hitbox sizes are 3.5 and share the same data as the inner

Corrin Up B Nightly
Initial
![Corrin Up B Initial N](https://user-images.githubusercontent.com/105788245/217467330-7cc67a85-9ee6-4236-8908-2e7f2011bcd2.png)
Multihit
![Corrin Up B Multihit N](https://user-images.githubusercontent.com/105788245/217467356-93b54e59-02c2-45ec-9cbf-c15352c4dcc3.png)
Launcher
![Corrin Up B Launcher N](https://user-images.githubusercontent.com/105788245/217467376-01373bd7-29e4-406f-a2a7-5a6a2f3175a8.png)

Corrin Up B PR
Initial
![Corrin Up B Initial PR](https://user-images.githubusercontent.com/105788245/217462441-0e4c08ba-2d12-4ac8-98c9-39be44e64910.png)
Multihit
![Corrin Up B Multihit PR](https://user-images.githubusercontent.com/105788245/217462462-660c641a-75d3-4155-9d0b-6413c44860a9.png)
Launcher
![Corrin Up B Launcher PR](https://user-images.githubusercontent.com/105788245/217462473-cbaed82c-bfec-489f-9df7-4a1b74c4e9bd.png)

2023-02-24 00:30 UTC, jobrien97 requested changes
game_specialsattack/game_specialairsattack should not be removed

2023-02-27 18:37 UTC, jobrien97 requested changes
The multihit hitlag mul should remain at 0.7, because the rehit rate is 2 (less than 4)

2023-03-22 16:57 UTC, hdr-balance-backroom commented
Please keep the previous hitboxes for upB's launcher, just shift them down a bit to make it less disjointed.

2023-03-27 16:27 UTC, jobrien97 approved these changes

2023-03-27 16:27 UTC, merged