Sephiroth Balance Adjustments
HDR-Development/HewDraw-Remix pull request #1418
Opened 2023-03-01 05:53 UTC by yoonikoo

Sephiroth range has proven to be oppressive his current state. These changes aim to tone down the sizes of his hitboxes and decrease his weight to remedy this issue.

<== SEPHIROTH ==>

General
~[-] Weight decreased from 90 to 80

Ftilt
~[R] Repositioned hitboxes to match sword
~[-] Head hitbox size reduced from 3.0 to 2.5
~[-] Normalized sourspot hitbox sizes from 4.0 to 3.0
~[-] Normalized sweetspot hitbox sizes from 4.5 to 3.5

FAIR
~[-] No longer autocancels from SH no FF

BAIR
~[R] Repositioned shoulder hitbox to clavicle
~[R] Repositioned hitboxes to match sword
~[R] Adjusted effects to match visuals
~[-] Clavicle hitbox size reduced from 3.5 to 2.0
~[-] Normalized sourspot hitboxes from 4.0 to 3.0
~[-] Normalized sweetspot hitbox sizes from 5.0 to 3.5

UAIR
~[R] Repositioned hitboxes to match sword
~[-] Arm hitbox sized reduced from 3.5 to 2.5
~[-] Normalized sourspot hitbox sizes from 4.0 to 3.0
~[-] Normalized sweetspot hitbox sizes from 4.5 to 3.5

FSmash
~[-] Normalized sourspot hitbox sizes from 4.0 to 3.0
~[-] Normalized sweetspot hitbox sizes from 5.0 to 3.5

USmash
~[R] Removed interpolating hitboxes
~[+] Added 2nd sweetspot hitbox
~[-] Normalized sourspot hitboxes from 4.0 to 3.0
~[-] Normalized sweetspot hitbox sizes from 5.0 to 3.5

BAIR (Current)
![Sephiroth BAIR Nightly](https://user-images.githubusercontent.com/105788245/222053411-63ab0734-accf-4952-b26c-4b13080779e8.png)
BAIR (New)
![Sephiroth BAIR PR](https://user-images.githubusercontent.com/105788245/222055604-202d2bda-333e-4e59-9327-fc32a51ccbe5.png)
Fsmash (Current)
![Sephiroth FSmash Nightly](https://user-images.githubusercontent.com/105788245/222055673-b64ab697-1271-4f11-a6d4-cffd8c188acd.png)
Fsmash (New)
![Sephiroth FSmash PR](https://user-images.githubusercontent.com/105788245/222055697-a1dc7767-2208-48e7-80be-6c7fb5f824ad.png)
Ftilt (Current)
![Sephiroth Ftilt Nightly](https://user-images.githubusercontent.com/105788245/222055737-56b581ec-6403-48c3-ac80-38243b0f83c6.png)
Ftilt (New)
![Sephiroth Ftilt PR](https://user-images.githubusercontent.com/105788245/222055784-db9f0b81-253c-40d8-971a-421eb55cb7d8.png)
FtiltD (Current)
![Sephiroth FtiltD Nightly](https://user-images.githubusercontent.com/105788245/222055898-95c5d07f-4634-4bdc-89a9-3ac68bc927c2.png)
FtiltD (New)
![Sephiroth FtiltD PR](https://user-images.githubusercontent.com/105788245/222055980-dfbf54a1-76d8-4ad7-903d-6c3e99683bcd.png)
FtiltU (Current)
![Sephiroth FtiltU Nightly](https://user-images.githubusercontent.com/105788245/222056029-9ad05782-1965-44ef-a592-59ce61ac98af.png)
FtiltU (New)
![Sephiroth FtiltU PR](https://user-images.githubusercontent.com/105788245/222056056-4026f490-31d8-455f-9a57-2780a429a2e7.png)
UAIR 1 (Current)
![Sephiroth UAIR 1 Nightly](https://user-images.githubusercontent.com/105788245/222056093-f1c566ea-7d81-47cc-b985-e57f0893b2a9.png)
UAIR 1 (New)
![Sephiroth UAIR 1 PR](https://user-images.githubusercontent.com/105788245/222056128-a0229bfe-c9a6-4ca3-8be9-57feccb6ec6a.png)
UAIR 2 (Current)
![Sephiroth UAIR 2 Nightly](https://user-images.githubusercontent.com/105788245/222056183-5cc68b25-ec0d-40a4-a806-18ebf23775f1.png)
UAIR 2 (New)
![Sephiroth UAIR 2 PR](https://user-images.githubusercontent.com/105788245/222056210-411be2a6-a1ec-479f-8ba1-6e3d7cf05695.png)
Upsmash 1 (Current)
![Sephiroth Upsmash 1 Nightly](https://user-images.githubusercontent.com/105788245/222056258-5703a4cc-989c-49af-940e-737ddaf5cddf.png)
Upsmash 1 (New)
![Sephiroth Upsmash 1 PR](https://user-images.githubusercontent.com/105788245/222056295-9321e068-2d05-4256-9a47-b1df300883a9.png)
Upsmash 2 (Current)
![Sephiroth Upsmash 2 Nightly](https://user-images.githubusercontent.com/105788245/222056346-1e0ae379-bd6b-4633-9662-c4d0fbde4813.png)
Upsmash 2 (New)
![Sephiroth Upsmash 2 PR](https://user-images.githubusercontent.com/105788245/222056399-61bbc413-1925-4989-908c-7b14c29f7907.png)
Upsmash 3 (Current)
![Sephiroth Upsmash 3 Nightly](https://user-images.githubusercontent.com/105788245/222056491-2c5ff0d8-f14a-48f2-8859-7d91cc47e7b0.png)
Upsmash 3 (New)
![Sephiroth Upsmash 3 PR](https://user-images.githubusercontent.com/105788245/222056542-f594dc18-c741-48dd-a0dd-4a17fe597bdf.png)

2023-03-13 04:33 UTC, hdr-balance-backroom submitted a review, later dismissed
- Reduce sword size very slightly (sorry, again) to match where vanilla's hitboxes end, adjust outermost hitbox to only cover the edge of the new length
- Change scoop hitbox of utilt from 368 to 95-100, remove intangibility
- Lower late dtilt angle to 70
- Lower late dash attack angle to 361
- Change both early and late fair angle to 361
- Increase ground-only dair bkb

2023-03-16 22:04 UTC, yoonikoo commented
> * Reduce sword size very slightly (sorry, again) to match where vanilla's hitboxes end, adjust outermost hitbox to only cover the edge of the new length
> * Change scoop hitbox of utilt from 368 to 95-100, remove intangibility
> * Lower late dtilt angle to 70
> * Lower late dash attack angle to 361
> * Change both early and late fair angle to 361
> * Increase ground-only dair bkb

Implemented the changes. Ready for review.

2023-03-26 03:36 UTC, SkewedAskew requested changes
Fsmash's outermost hitbox should line up with the trail's edge
Ftilt needs that bright white trail to align with the outermost hitbox (don't forget the angled versions as well)
Looks good otherwise
![image](https://user-images.githubusercontent.com/55216313/227753589-9bfe4690-f6af-4791-8ffc-6fff9d3caf99.png)
![image](https://user-images.githubusercontent.com/55216313/227753672-7bd357f4-cd4e-46a7-a682-13eb96972fa0.png)

2023-03-26 22:41 UTC, SkewedAskew approved these changes

2023-03-26 22:55 UTC, merged