Revert wallride opff, slight buff on bf distance, added 2nd weak hit to dsmash
HDR-Development/HewDraw-Remix pull request #1431
Opened 2023-03-08 18:32 UTC by stingers135

- Wallride OPFF was not functioning, sheik was not able to wallride her upb. Reverted to previous implementation with no code changes made.

- Feedback on bouncing fish was that it did not go far enough with the previous nerfs. Added slight range increase (previously 47% of Vanilla distance, now 60% of Vanilla distance)

- Added a second hit to Dsmash to match melee behavior, moved weak hitboxes back 1f

2023-03-13 04:22 UTC, hdr-balance-backroom requested changes
- Wallride code reversion can be reverted as it is being removed in another PR
- Please post comparisons of old/new Bouncing Fish distances

2023-03-13 21:12 UTC, stingers135 commented
@hdr-balance-backroom @SkewedAskew 

Old:
https://user-images.githubusercontent.com/115596132/224833122-7a6939ba-b350-4fcf-8c0a-0f87e97f7934.mp4

New:
https://user-images.githubusercontent.com/115596132/224833424-16ffcea0-65f6-4ae1-b2ac-13674ecbeffc.mp4

2023-03-14 16:21 UTC, jobrien97 commented
Please just revert the changes to her opff.rs file. Vanish wallriding is getting removed in a separate PR

2023-03-17 03:00 UTC, jobrien97 approved these changes
lgtm

2023-03-17 03:11 UTC, merged