Duck Hunt Adjustments
HDR-Development/HewDraw-Remix pull request #1556
Opened 2023-04-16 05:26 UTC by yoonikoo

This is a take on my ideas of how to nerf Duck Hunt. These adjustments are subject to changes.

These changes aim to tone down Duck Hunt, who has infamously become considered to be "overtuned" over the past couple of months. These changes bring Duck Hunt to HDR's current balance philosophy.

<== DUCK HUNT ==>

GENERAL
~[-] Duck is no longer intangible at anytime
~[-] Grab box size decreased from 4.5 to 4.0
~[-] Grab box length decreased from 11.7 to 8.7

GROUND

-Dash Attack
~[-] Kinetic energy decreased from 0.94 to 0.8
~[R] Added another hitbox to Duck 
~[R] Early hit angle changed from 60 to 50
~[R] Early hit BKB changed from 100 to 70
~[-] Early hitbox sizes decreased from 5.5 to 4
~[R] Late hit angle changed from 105 to 50
~[R] Late hit BKB changed from 90 to 60

-Jab 1
~[-] Removed the 1f added hitstun
~[-] Removed an unnecessary hitbox
~[R] Angle changed from 70 to 361
~[-] Hitlag decreased from 1.6 to 1.0

-Jab 2
~[-] Removed the 1f added histstun
~[R] Angle changed from 70 to 361
~[-] Hitlag decreased from 1.2 to 1.0

-Jab 3
~[R] Added another hitbox to Dog
~[R] Angle changed from 70 to 361
~[-] Hitlag decreased from 2.0 to 1.0

TILTS

-Ftilt
~[R] Attached hitboxes to Duck on all variants
~[R] Added additional hitbox on all variants
~[R] Removed ass hitbox on all variants
~[-] Nontipper hitbox damage decreased from 8 to 7
~[-] Decreased hitbox sizes from 3.5/4.5 to 3.5/4.0 on all variants
~[-] Hitlag decreased from 1.15 to 1.0 on all variants

-Utilt
~[-] First hitbox appearance changed from frame 4 to 8
~[R] Added additional hitbox to Duck

-Dtilt
~[R] Attached hitboxes to Duck
~[R] Added additional hitbox to Duck
~[-] FAF increased from 27 to 33

AERIALS

-NAIR
~[-] Pushed from 3f to 6f
~[-] Early hit damage decreased from 13 to 11
~[-] Early hit KBG decreased from 95 to 90
~[-] Early hitbox sizes decreased from 4.5 to 4.0
~[-] Late hit KBG decreased from 90 to 85
~[-] Late hitbox sizes decreased from 3.5 to 3.0
~[-] Late hit active frames decreasd from 29 to 15

-FAIR
~[R] Normalized hitboxes to appear at frame 8 than 7/8
~[R] Added extra hitbox to Duck
~[-] Active frames decreased from 6 to 5
~[R] Early hit active frames changed from 7-10 to 8-10
~[-] Hitbox sizes decreased from 5.0/5.5 to 3.5/4.0
~[-] No longer autocancelable on SHFF

-BAIR
~[R] Added extra hitbox to Duck
~[-] Active frames changed from 8 to 7
~[R] Late hit active frames changed from 11-14 to 11-13
~[-] Early hit damage decreased from 11 to 9.5
~[-] Early hit tipper damage decreased from 13.5 to 12
~[R] Early hit tipper KBG changed from 104 to 105
~[-] Late hit damage changed from 11 to 9.5
~[-] No longer autocancelable out of "SH no FF"

-UAIR
~[R] Priority changed
~[R] Added another hitbox to Duck
~[-] UAIR 1&2 hitbox sizes decreased from 4.0/6.0 to 3.5/4.0
~[-] UAIR launcher hitbox sizes decreaed from 5.0/8.5 to 4.0/6.0

-DAIR
~[-] DAIR 1 hitbox sizes decreased from 5.5/4.0 to 4.5/3.5
~[-] DAIR 2 hitbox sizes decreased from 6.5 to 4.5

SPECIALS

-Neutral B
~[-] Can release frame increased from 8.0 to 12.0

Hitbox Changes:

Old: 
Jab 1:
![Jab 1](https://user-images.githubusercontent.com/105788245/232272333-9616306e-f29f-45e3-ae35-ddee49e8a150.png)
Jab 3: 
![Jab 3 Gentleman](https://user-images.githubusercontent.com/105788245/232272343-f1e87fac-ff97-4f6e-ac15-42926dd15fdd.png)
Dash Attack (Early):
![DA Early](https://user-images.githubusercontent.com/105788245/232272843-c65f5483-2ff8-488d-ba9f-6f021d009736.png)
Dash Attack (Late):
![DA Late](https://user-images.githubusercontent.com/105788245/232272846-318fd7a5-9785-4841-96f4-2728856561c4.png)
Ftilt (High):
![Uptilt High](https://user-images.githubusercontent.com/105788245/232272469-17208c02-e8cc-4d17-809c-f63d3901bc05.png)
Ftilt:
![Ftilt](https://user-images.githubusercontent.com/105788245/232272836-6559123e-48fa-4e0b-b245-8a4cfca78f71.png)
Ftilt (Low):
![Uptilt Low](https://user-images.githubusercontent.com/105788245/232272479-48cb045c-f332-4877-905b-08c5471c1940.png)
Up Tilt:
![Uptilt](https://user-images.githubusercontent.com/105788245/232272493-1aedfe19-885a-4110-9945-2e806e59ab41.png)
Down Tilt:
![Downtilt](https://user-images.githubusercontent.com/105788245/232272497-d4bc3072-4686-4a6b-a95b-d83ebb870115.png)
NAIR (Early):
![NAIR Early](https://user-images.githubusercontent.com/105788245/232272505-32cd7bc1-de24-428d-a532-73549cbb8f28.png)
NAIR (Late):
![NAIR Late](https://user-images.githubusercontent.com/105788245/232272509-068670cd-77e5-4a25-acb4-eb77c56c7cb6.png)
FAIR:
![FAIR](https://user-images.githubusercontent.com/105788245/232272519-6c683e6f-fac7-4565-8b8e-9b82e0abbba1.png)
BAIR:
![BAIR](https://user-images.githubusercontent.com/105788245/232272526-153e84e8-9a3c-4e14-927a-29e9c3e6fa3b.png)
Up Air:
![UAIR 1](https://user-images.githubusercontent.com/105788245/232272535-126e9833-c534-4621-a653-6a824598f55b.png)
![UAIR 2](https://user-images.githubusercontent.com/105788245/232272539-aebcfaf4-b688-4d46-ae8d-468291d93e6e.png)
![UAIR 3](https://user-images.githubusercontent.com/105788245/232272542-d5c1ee56-3ea1-4dc2-8807-0e65939e91c3.png)
DAIR:
![DAIR 1](https://user-images.githubusercontent.com/105788245/232272555-183635c0-6289-4300-8980-5ee103cc9022.png)
![DAIR 2](https://user-images.githubusercontent.com/105788245/232272559-39527cff-51ab-477a-828a-4277868c72c9.png)
Grab:
![Grab](https://user-images.githubusercontent.com/105788245/232272565-7b26be57-4a29-4fa0-9882-d4f3e44b7e21.png)

New:
Jab 1:
![Jab 1](https://user-images.githubusercontent.com/105788245/232272124-014072be-dfd5-4c76-83d5-3c90bbce7d68.png)
Jab 3:
![Jab 3](https://user-images.githubusercontent.com/105788245/232272146-bb3a0153-f980-4493-add1-851d5dcbcba9.png)
Dash Attack (Early):
![DA Early](https://user-images.githubusercontent.com/105788245/232272151-c13b876d-def8-420c-a015-9f9a12ceee46.png)
Dash Attack (Late):
![DA Late](https://user-images.githubusercontent.com/105788245/232272155-7c6e6674-2c0a-42aa-98d4-545d0e08cfce.png)
Ftilt (High):
![Ftilt High](https://user-images.githubusercontent.com/105788245/232272180-86fd04e1-0def-4bdb-84a3-4ea2d716ce54.png)
Ftilt:
![Ftilt](https://user-images.githubusercontent.com/105788245/232272200-0fe3d95f-0883-4f9d-904b-4d746347151c.png)
Ftilt (Low):
![Ftilt Low](https://user-images.githubusercontent.com/105788245/232272206-87d27413-1452-4cc5-bd54-559d0c0ab440.png)
Up Tilt:
![Uptilt](https://user-images.githubusercontent.com/105788245/232272211-bf4aa47b-bbe1-4232-97cc-a66ad1f53aa7.png)
Down Tilt:
![Downtilt](https://user-images.githubusercontent.com/105788245/232272226-e9c7669d-09d1-41a9-8914-eaf11ac872d4.png)
NAIR (Early): 
![NAIR Early](https://user-images.githubusercontent.com/105788245/232272438-95f382dd-b0cb-4d67-87d2-f92b169ee698.png)
NAIR (Late):
![NAIR Late](https://user-images.githubusercontent.com/105788245/232272451-a7b3479d-422b-42f2-8c02-7af048c74461.png)
FAIR (Early):
![FAIR Early](https://user-images.githubusercontent.com/105788245/232272233-bd59ec8d-b309-4813-83c1-b0c35dc8fb11.png)
FAIR (Late):
![FAIR Late](https://user-images.githubusercontent.com/105788245/232272241-f276cb19-aff3-4288-8566-73967f94837d.png)
BAIR (Early):
![BAIR Early](https://user-images.githubusercontent.com/105788245/232272261-79adb9fc-7fa6-43a5-abc9-a80dabbceada.png)
BAIR (Late):
![BAIR Late](https://user-images.githubusercontent.com/105788245/232272268-30937b81-8005-4496-9cac-88a70dd556a5.png)
Up Air:
![UAIR 1](https://user-images.githubusercontent.com/105788245/232272285-6c5241c8-1f83-4fd2-a264-f54edae49935.png)
![UAIR 2](https://user-images.githubusercontent.com/105788245/232272288-0b0c62aa-56f9-4153-8466-3c7b30fae776.png)
![UAIR 3](https://user-images.githubusercontent.com/105788245/232272290-4ec32d4c-5a2a-414e-8f41-f368977d1fa3.png)
DAIR:
![DAIR 1](https://user-images.githubusercontent.com/105788245/232272294-d0ac0fda-46b1-4d99-ac9b-df4f45a1289f.png)
![DAIR 2](https://user-images.githubusercontent.com/105788245/232272295-8b8b18c2-04aa-4c3f-b10c-394fe05485fc.png)
Grab:
![Grab](https://user-images.githubusercontent.co [...]

2023-04-30 23:25 UTC, hdr-balance-backroom requested changes
- Reduce Clay Pigeon hitlag (both on contact and the multihits), increase endlag by ~8-10 frames

2023-05-29 01:16 UTC, yoonikoo commented
> * Reduce Clay Pigeon hitlag (both on contact and the multihits), increase endlag by ~8-10 frames

Done

2023-06-07 00:10 UTC, hdr-balance-backroom requested changes, later dismissed
- Increase grab range from 8.7 -> 9.7
- Revert utilt hitbox changes on duck (dog hitbox stays the same size)
- Change utilt hitbox active to frames 7-11 and increase hitbox activity on dog by one frame (frames 7-8)
- Increase active frames on each jab by 1 frame
- Change late hit nair activity to match vanilla behavior (revert clear to frame 38) 
- Revert nair early hit kb changes (damage decrease will still remain)
- Make ID 1 hitbox on fair, bair, ftilt, and dtilt match the sweetspot (the beak hitbox)
- Revert bair damage and kb decrease
- Revert autocancel frame change and instead motion rate the auto cancel (to the same frame) to match the timing for when the duck returns back to the dog
- Revert can release frame to frame 8
- Increase uair hit 1 and hit 2 hitbox sizes by 1.0 and match the impact effects to the duck's beak
- Revert dair hitbox sizes (so back to the original capsule hitbox on second hit), and decrease the second hitbox size by about 0.5-1.0 units
- Revert late dash attack angle and kb

2023-06-11 05:31 UTC, SkewedAskew approved these changes

2023-06-11 05:32 UTC, merged