Sephiroth Uptilt Hotfix
HDR-Development/HewDraw-Remix pull request #1562
Opened 2023-04-18 23:00 UTC by yoonikoo

Will no longer instakill off the side

2023-05-04 20:12 UTC, SuddyN submitted a review, later dismissed

2023-05-14 05:14 UTC, jobrien97 requested changes, later dismissed
Scoop hitbox just doesn't work anymore now. I don't think outright removing `set_vec_target_pos` is the move here

2023-05-21 21:01 UTC, SkewedAskew approved these changes, later dismissed

2023-06-07 00:10 UTC, hdr-balance-backroom requested changes, later dismissed
- Fix knockback on the scoop hitbox (currently has 0 bkb) and change the angle to 100

2023-06-11 07:46 UTC, SkewedAskew approved these changes

2023-06-11 07:50 UTC, merged