Gordo redesign and dedede adjustments
HDR-Development/HewDraw-Remix pull request #1642
Opened 2023-05-31 16:33 UTC by SirTanknSpank

Big adjustments for the big penguin and his funny spike ball to make him less gordo centric, but keeping gordo as a incredibly low knockback tool that sets up dedede for combos or pressure. Oh and a few other things too.

Assets: [dedede-assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/11615964/dedede-assets.zip)

# Changelog

### Gordo Throw

- [!] New animations, based off of brawl's waddle dee toss
- [-] Hammer hitbox removed
- [-] Regrab removed
- [+] Startup: Frame 29 --> 18
- [+] FAF: Frame 58 --> 49
- [-] Now has a cooldown of 360 frames (6 seconds) AFTER gordo despawns.
    - Dedede cannot side b while gordo is on cooldown
- [!] Can now ~~waddle~~dash by holding shield while doing side b on the ground
    -  This can slide off of ledges

https://github.com/HDR-Development/HewDraw-Remix/assets/115139386/3b15bc72-4c21-4f4e-838a-280d40e1cdb4

https://github.com/HDR-Development/HewDraw-Remix/assets/115139386/5c92644a-45c0-4628-94c7-58f7888a5ef9

https://github.com/HDR-Development/HewDraw-Remix/assets/115139386/27ae94a7-f392-446e-aae3-edabd4b3cfff

### Gordo (the projectile)
- [!] Damage is based off of how many times it bounces, rather than how long it has been active
- [-] Damage: 14/12.5/11/9.5 (changing every 30 frames) --> 10/9/8/7 (changing on every bounce)
- [+] KBG: 120
- [-] BKB: 0
- [+] FKB: 60
- [+] Vanishes upon being hit with an attack doing 5% or greater, rather then being sent back with a hitbox
    - This means that Gordo can no longer hit Dedede unless reflected or parried
- [-] Bounce Height Multiplier: 1.15x --> 1.05x
- [-] Hop life (the state gordo goes into after hitting someone): 60 -> 45 

### Gordo Shot (Inhaled Gordo)
- [!] Damage is based off of how many times it bounces, rather than how long it has been active
- [-] Damage: 16.8/15.0/13.2/11.4 (changing every 30 frames) --> 12.8/11.2/9.6/8.0 (changing on every bounce)
- [-] Angle: 40 --> 60
- [-] KBG: 66 --> 50
- [-] BKB: 70 --> 60

### Down Tilt
- [!] New animation
- [-] Startup: 6 --> 7
- [+] Angle: 40 --> 361
- [+] Initial Hit KBG: 80 --> 100
- [+] Late Hit KBG: 80 --> 100
- [-] Initial Hit BKB: 50 --> 30
- [-] Late Hit BKB: 50 --> 30
- [-] Late Hit damage: 8.0 --> 6.0

https://github.com/HDR-Development/HewDraw-Remix/assets/115139386/202c538f-8f1d-401c-8efa-84d0a8cb67cd

### Forward Air
- [-] KBG: 100 --> 94
- [+] Autocancel Window: 1-4, 35+
    - Can now autocancel from a shorthop

### Inhale
- [-] End Lag: 19 --> 25

### Side Taunt
[+] Fixed the bugged animation from vanilla ultimate

2023-06-23 01:19 UTC, hdr-balance-backroom submitted a review, later dismissed
- Fair should be position-based
- Revert fair autocancel window
- Consider removing the lockout on Gordos as they don't seem to warrant it

2023-06-23 14:43 UTC, SkewedAskew requested changes

2023-06-23 14:43 UTC, SkewedAskew commented on fighters/common/src/function_hooks/transition.rs
> +        if boma.kind() == *FIGHTER_KIND_DEDEDE {
This can be removed as well

2023-06-23 14:43 UTC, SkewedAskew commented on dynamic/src/consts.rs
> +            pub const GORDO_TIMER: i32 = 0x0100;
Since Gordos are no longer on a timer, this can be removed

2023-06-24 16:40 UTC, SkewedAskew approved these changes

2023-06-24 17:04 UTC, merged