Infinite Jump Hotfix, couple errors, removes poorly implemented effect
HDR-Development/HewDraw-Remix pull request #1673
Opened 2023-06-12 01:34 UTC by jaccob101

Changes implementation of jump refresh to be more foolproof, some what I believe to be merge errors and the glitched effect

2023-06-17 17:45 UTC, jaccob101 commented
I believe i've fixed all the bugs i've noticed and knew how to fix, lmk if I made any errors or if theres a better way to fix things

2023-06-25 21:46 UTC, SkewedAskew requested changes

2023-06-25 21:46 UTC, SkewedAskew commented on fighters/bayonetta/src/acmd/tilts.rs
> +        ATTACK(fighter, 3, 0, Hash40::new("armr"), 2.0, 135, 27, 0, 60, 5.0, 6.0, 0.0, 0.0, None, None, None, 0.8, 0.0, *ATTACK_SETOFF_KIND_ON, *ATTACK_LR_CHECK_F, true, 0, 0.0, 0, false, false, fals
While id2 does override this hitbox when in contact with aerial opponents, please change id3 to ground-only for consistency

2023-07-01 01:03 UTC, jaccob101 commented
Ok got everything I can do on my own done. Includes the code review. I can't figure out how to shorten ABK or make ftilt 3 work if I check for special input.

2023-07-01 14:59 UTC, SkewedAskew requested changes
- Performing a shorthop, inputting ABK on the first frame of being airborne, and then pressing down on frame 2 of the move will still perform DABK
- Ftilt3 is actually 36 FAF, not 37
- Ftilt3 can no longer be performed using Special

2023-07-01 17:21 UTC, jaccob101 commented
> * Performing a shorthop, inputting ABK on the first frame of being airborne, and then pressing down on frame 2 of the move will still perform DABK
> 
>     * Ftilt3 is actually 36 FAF, not 37
> 
>     * Ftilt3 can no longer be performed using Special

i cant find out how to fix the first one but i fixed the ftilt 3 special input by changing motion and disabling the combo flag (kept forcing ftilt 2)

2023-07-05 18:53 UTC, hdr-balance-backroom submitted a review, later dismissed
- Revert ftilt 3's endlag decrease (the reduced startup is fine, FAF should be 39 as a result)
- Remove the ability to hold special to not slide off ledge during Heel Slide

2023-07-05 19:11 UTC, jaccob101 commented
> - Revert ftilt 3's endlag decrease (the reduced startup is fine, FAF should be 39 as a result)
> - Remove the ability to hold special to not slide off ledge during Heel Slide

Done, my bad. I just realized that the heelslide kick status is prob separate anyways so it'll prob make more sense that way anyways

2023-07-08 21:19 UTC, SkewedAskew approved these changes

2023-07-08 22:22 UTC, merged