Dark Samus adjustments (+ Samus)
HDR-Development/HewDraw-Remix pull request #1732
Opened 2023-07-01 17:24 UTC by SkewedAskew

# Changelog
## Dark Samus
### General
 - [+] Dash Speed: 1.674 -> 1.86
 - [-] Run Acceleration Multiplier: 0.10113 -> 0.1
 - [+] Jump Speed Multiplier: 0.8x -> 0.95x
 - [-] Max Horizontal Jump Speed: 1.34 -> 1.3
 - [-] Air Acceleration Multiplier: 0.045 -> 0.015
 - [/] Air Friction: 0.0125 -> 0.01
 - [/] Gravity: 0.076 -> 0.085
 - [/] Fallspeed: 1.43 -> 1.87
 - [/] Fast Fall Speed: 2.24 > 2.604
 - [/] Hitstun Gravity: 0.1 -> 0.09
 - [/] Hitstun Fallspeed: 1.55 -> 1.87

### Jab 1
 - [-] Hitboxes moved inward and downward slightly
 - [-] Angle: 70 -> 60
 - [-] Additional Hitstun: 1F -> 0F
 - [-] Hitbox Size (arm): 4.0u -> 3.5u

### Forward Tilt
 - [+] Damage (hip/knee/foot/back knee): 10.5/11.5/12.5/10.5% -> 12.0/13.0/13.0/12.0%
 - [=] KBG: 105 -> 102

### Up Tilt
 - [+] Damage: 12.5% -> 14.0%
 - [=] BKB (ground/air): 46/40 -> 48/42
 - [=] KBG (ground/air): 105/94 -> 95/85

### Forward Smash
 - Early
   - Sweetspot
     - [/] Damage (high/mid/low): 15.5/15.0/14.5% -> 15.0/16.0/15.0%
       - [=] BKB: 40 -> 41
       - [=] KBG: 105 -> 99
   - Sourspot
     - [/] Damage (high/mid/low): 13.5/13.0/12.5% -> 13.0/14.0/13.0%
       - [=] BKB: 30 -> 31
       - [=] KBG: 100 -> 94

### Up Smash
 - [R] Changed to a single hit
 - [$] Animation timing adjusted
 - Hitbox Duration (early/late): F11-14/F15-19
 - Damage (early/late): 15.0/11.0%
 - Angle: 80
 - BKB: 80
 - KBG: 75
 - Hitlag Multiplier: 0.8x
 - Hitbox Size (shoulder/cannon): 4.5/5.0u
 - [+] FAF: 62 -> 52

### Down Smash
 - Early
   - Body
     - [+] Damage: 13.0% -> 15.0%
     - [=] BKB: 40 -> 42
     - [=] KBG: 105 -> 93
   - Phazon
     - [-] Lower end moved upwards 1.5u
     - [+] Damage: 15.0% -> 17.0%
     - [=] BKB: 40 -> 42
     - [=] KBG: 108 -> 96
       - [/] Hitlag Multiplier: 1.25x -> 1.0x
 - Mid
   - Phazon Base
     - [-] Lower end moved upwards 1.5u
     - [=] BKB: 40 -> 42
     - [=] KBG: 108 -> 96
   - Phazon Tip
     - [-] Damage: 15.0% -> 14.0%
     - [=] BKB: 38 -> 40
       - [=] KBG: 108 -> 101
 - Late
   - Body
     - [-] KBG: 105 -> 101
   - Phazon Base
     - [-] Lower end moved upwards 1.5u
     - [+] Damage: 13.5% -> 14.0%
       - [-] Angle (tip): 72 -> 70
     - [=] BKB: 38 -> 40
     - [=] KBG: 108 -> 101
       - [/] Hitlag Multiplier: 1.25x -> 1.0x
   - Phazon Tip
     - [-] Angle: 72 -> 70
       - [=] BKB: 38 -> 40
       - [=] KBG: 108 -> 101
       - [/] Hitlag Multiplier: 1.25x -> 1.0x

### Neutral Air
 - Launcher
   - [+] Damage: 4.0% -> 6.4%
   - [=] BKB: 46 -> 52
   - [=] KBG: 110 -> 78

### Forward Air
 - [+] Elbow hitbox matched to hand hitbox
 - Shoulder
   - [+] Damage: 9.5% -> 10.0%
   - [=] KBG: 77 -> 74
 - [+] Autocancel: F34 -> F1-3/F34

### Back Air
 - [$] Adjusted animation timing
 - [$] Adjusted vfx
 - [-] Hitbox Duration (early/late): F8-9/F10-22 -> F8-10/F11-16
 - Early
   - [+] Damage (leg/foot): 11.0/13.0% -> 12.0/15.0%
   - [=] BKB: 42 -> 44
   - [=] KBG: 102 -> 90
   - [/] Hitlag Multiplier: 1.1x -> 1.0x
 - [-] Landing Lag: 12F -> 13F

### Down Air
 - Early
   - [+] Damage: 13.0% -> 14.0%
   - [=] BKB: 25 -> 26
   - [=] KBG (ground/air): 80/55 -> 75/51
 - Late
   - [+] Damage: 10.0% -> 11.0%
   - [=] BKB: 45 -> 46
   - [=] KBG: 65 -> 60

### Missiles
 - [R] Removed super missiles
 - Late
   - [+] Damage: 10.0% -> 12.0%
   - [=] BKB: 26 -> 28
   - [=] KBG: 55 -> 47

### Screw Attack
 - [+] Initial Speed: 2.5 -> 2.85

### Bomb
 - [R] Removed the ability to manually detonate the bomb
 - [$] Adjusted vfx
 - [-] Lifetime: 240F -> 180F
 - [R] Bounce Height Multiplier: 0.0x -> 1.0x
 - [-] Hitbox Duration: F1-13 -> F1-4

## Samus
### General
 - [-] Dash Speed: 1.86 -> 1.674
 - [+] Run Acceleration Multiplier: 0.1 -> 0.10113
 - [-] Jump Speed Multiplier: 0.95x -> 0.8x
 - [+] Max Horizontal Jump Speed: 1.3 -> 1.34
 - [+] Air Acceleration Multiplier: 0.015 -> 0.045
 - [/] Air Friction: 0.01 -> 0.0125
 - [/] Gravity: 0.085 -> 0.076
 - [/] Fallspeed: 1.87 -> 1.43
 - [/] Fast Fall Speed: 2.604 > 2.24
 - [/] Hitstun Gravity: 0.09 -> 0.1
 - [/] Hitstun Fallspeed: 1.87 -> 1.55

### Screw Attack
 - [-] Initial Speed: 2.85 -> 2.5

2023-08-07 01:25 UTC, SuddyN reviewed
resolve conflicts to be reviewed

2023-08-08 00:52 UTC, h3ra-ai2020 requested changes
- Dark Samus's up smash whiffs on short foes. Is this intentional?
- Dark Samus's forward air deals less damage with the claw swipe than with the shoulder. Is this intentional? If so, the sound levels should be adjusted, as the weaker hit sounds stronger than the stronger hit.

2023-08-08 01:43 UTC, SkewedAskew commented
For clarity, up smash has always whiffed on shorter characters

2023-08-08 01:49 UTC, h3ra-ai2020 approved these changes

2023-08-08 02:00 UTC, merged