Ness Side B Recoil Fix + Up B buffs
HDR-Development/HewDraw-Remix pull request #1857
Opened 2023-07-31 02:00 UTC by O1yyy

high level interpretation of the changes:

### pkthunder
- pkt2 blue screen removed
- pkt1's hover is much better, negligible fall acceleration now
- turning angle on pkt1 ball buffed, should make chosing angles feel a little better
- you can drift much sooner after pkt2 ends
- fixed wall collision, no longer dies on walls
- ~~now grabs ledge behind him while at peak pkt2 (nutty underside angles are now possible)~~
  - this still doesnt work, need help
### pkfire
- pkfire no longer recoils

2023-07-31 06:24 UTC, O1yyy commented
i dont THINK i need `rom_watch.txt` as part of this pr, if anyone knows what's explicitly needed to declare a new `hdr.xml`, please request the changes

2023-08-08 05:43 UTC, O1yyy commented
i left in an unfinished stall prevention script in ness's `status.rs`, if anyone with a bigger brain wants to help decipher the logic to make it work i will put it for both ness and lucas

2023-08-24 23:31 UTC, WuBoytH commented on fighters/ness/src/acmd/specials.rs
> +            ATTACK(fighter, 0, 0, Hash40::new("top"), 5.5, 361, 35, 0, 70, 2.5, 0.0, 6.5, 2.0, None, None, None, 0.5, 1.0, *ATTACK_SETOFF_KIND_OFF, *ATTACK_LR_CHECK_F, false, 0, 0.0, 20, false, false
Remove the 20 rehit rate on these hitboxes, I know it literally doesn't matter but like it does nothing

2023-08-24 23:45 UTC, h3ra-ai2020 requested changes, later dismissed
make sure `rom_watch.txt` is actually up to date

2023-08-24 23:45 UTC, h3ra-ai2020 commented on utils/agent_params.txt
> +miigunner: fighter/miigunner/param/hdr.prc
remove extra mii gunner

2023-08-25 00:48 UTC, hdr-balance-backroom submitted a review, later dismissed
- Document all changes, some are missing such as dthrow's angle and knockback change
- Revert dthrow FAF, readjust knockback to maintain relatively similar combo ability

2023-08-27 06:15 UTC, O1yyy commented
> * Document all changes, some are missing such as dthrow's angle and knockback change
> 
>     * Revert dthrow FAF, readjust knockback to maintain relatively similar combo ability

so about this, the dthrow angle was from riah's pr, which is documented there and i mention at the very top, any and all hitbox changes are from that pr, my pr only does what i note down to reduce redundancy

backroom looked at that pr in its completed state, dthrow angle and kb included, and this is all you requested that time:

![image](https://github.com/HDR-Development/HewDraw-Remix/assets/19886440/3a511de5-920d-45b0-92fd-122c09769f61)

this stuff i already did so thats taken care of 

so, besides reverting dthrow FAF, all of my changes are documented, and any other solid number changes are back in https://github.com/HDR-Development/HewDraw-Remix/pull/1770 here

2023-09-01 11:56 UTC, O1yyy commented
ready for review again, will refrain from touching it so that it can get into a beta

2023-09-16 12:16 UTC, Riah321 commented
"We'll leave it untouched"

9 commits later....

2023-09-19 16:05 UTC, WuBoytH approved these changes

2023-09-19 21:32 UTC, merged