Metaknight P+ Bair & Jab + animation/sfx tweaks
HDR-Development/HewDraw-Remix pull request #1918
Opened 2023-08-25 00:10 UTC by robertyur

**Assets:** [mk assets.zip](https://github.com/HDR-Development/HewDraw-Remix/files/12431027/mk.assets.zip)

Recreated P+ Bair, adjusted Jab to be more similar to P+, stopped MK from tap dancing at the end of Jab,  swapped air jump 4 animation with 5 to better clarify when MK is out of jumps, and lastly changed the kick sfx on Fsmash to a cut sfx because he's using a sword, dude.

**Bair:**
https://github.com/HDR-Development/HewDraw-Remix/assets/22902718/74b0b352-45c5-456d-b9cf-348e531e5c78
MK lacked variety in his aerials, so this is intended to change that by giving him a single hit, strong disjoint that combos at early percents and kills at later ones.
- Hitboxes active from frames 10-11
- DMG: 14%
- Angle: 361
- KBG: 100
- BKB: 30
- FAF: 36

**Jab:**
Current jab hits do not connect consistently and tend to send opponents away before the final hit connects if MK isn't right on top of them. I believe the current jab is good because it's fast- frame 4, while the rest of the move is underwhelming. These changes slow the move down slightly while making the entire move more consistently useful and imo, more inline with how other rapid jabs are balanced.

- Startup: 3 frames -> 6 frames

Frames 4-5 (are now) -> 7-8
- Angle: 361->95
- KBG: 8->40
- BKB: 40->25
- Added hitbox behind MK (will insert comparison pics later)
- DMG: 2%
- Angle: 60
- KBG: 40
- BKB: 25

Frames 8-9 -> 11-12
- Angle: 361->120
- KBG: 8->40
- BKB: 40->25

Frames 12-13 -> 15-16
- Angle: 361->120
- KBG: 8->40
- BKB: 40->25

Frames 17-18 -> 20-21
- DMG: 3%->2%
- Angle: 361->120
- BKB: 60->25

Frames 21-22 -> 24-25
- KBG: 40->100
- BKB: 60->40
- Hitbox size decreased
- Added hitbox infront of MK (will insert comparison pics later)
- DMG: 3%
- Angle: 361
- KBG: 100
- BKB: 40
- Hitbox size: 5
- Added hitbox covering MK (will insert comparison pics later)
- DMG: 3%
- Angle: 361
- KBG: 100
- BKB: 40
- Hitbox size 7.5

**P.S.** - If you know how to manipulate effect animations, i.e. make the Fsmash effect I'm using for this new Bair only play its last 2 frames as opposed to its first 2 frames (it's normally only 3 frames total), please let me know as I think that may look marginally better than what I have now.

2023-08-27 01:32 UTC, hdr-balance-backroom requested changes, later dismissed
- Please match bair's hitbox shape to how up air and down air are structured
- Revert jab changes for now

2023-08-28 08:14 UTC, robertyur commented
![image](https://github.com/HDR-Development/HewDraw-Remix/assets/22902718/f22823a8-8026-4620-8c74-edd415f522e8)
updated hitboxes

2023-08-30 18:09 UTC, robertyur commented
Should this reverse hit?

2023-08-30 22:03 UTC, SkewedAskew approved these changes

2023-08-30 22:15 UTC, merged