Implement Z-NAirs
HDR-Development/HewDraw-Remix pull request #2397
Opened 2024-05-08 23:11 UTC by SuddyN

Starting an aerial with the grab button will always use NAir, ignoring the left stick

2024-05-10 15:58 UTC, epic-bruh-moment commented
Is it possible to make it so that for robin Z-NAir will always be levin sword?

2024-05-13 14:39 UTC, WuBoytH requested changes

2024-05-13 14:39 UTC, WuBoytH commented on fighters/common/src/general_statuses/mod.rs
> +    VarModule::set_flag(fighter.battle_object, vars::common::instance::IS_Z_NAIR, catch_trigger_count < buffer);
Instead of hooking get_attack_air_kind please just use the ControlModule function that lets you directly set the attack air kind.

2024-05-17 01:22 UTC, peterwoodworth commented
This would be great to have, it's a feature in Rivals 2 and is a spiritual successor to achieving nair with c stick in PM

2024-10-06 03:18 UTC, closed without merging