Uncapped G2A Floats
HDR-Development/HewDraw-Remix pull request #2475
Opened 2024-07-31 14:56 UTC by jaccob101

Makes floats have uncapped motion transfer the same way aerials do, rather than instantly dropping to the air speed cap. Mostly affects Daisy but has been done to all floats.

2024-07-31 15:17 UTC, WuBoytH requested changes

2024-07-31 15:17 UTC, WuBoytH commented on fighters/daisy/src/status/uniq_float.rs
> +extern "Rust" {
please combine this extern "Rust" with the one below for cleanliness.

2024-08-01 20:26 UTC, WuBoytH approved these changes

2024-08-20 02:07 UTC, SkewedAskew commented
Not being considered at this time

2024-08-20 02:07 UTC, closed without merging