Double traction status added to standing grab
HDR-Development/HewDraw-Remix pull request #622
Opened 2022-06-01 18:26 UTC by MadVillainLordQ

Resolves Issue #621

2022-06-01 22:16 UTC, jobrien97 approved these changes, later dismissed
lgtm

2022-06-01 22:18 UTC, jobrien97 commented
On second thought, might want to include CATCH_WAIT (grab idle) and CATCH_ATTACK (pummel) as well

2022-06-02 14:38 UTC, jobrien97 requested changes

2022-06-02 14:38 UTC, jobrien97 commented on fighters/common/src/opff/physics.rs
> +        *FIGHTER_STATUS_KIND_CATCH.
Replace period with comma

2022-06-02 19:29 UTC, MadVillainLordQ commented on fighters/common/src/opff/physics.rs
> +        *FIGHTER_STATUS_KIND_CATCH.
Got it. Thanks for catching that.

2022-06-02 20:12 UTC, jobrien97 approved these changes

2022-06-03 02:13 UTC, merged