Rework aerial glide tossing (airdodge cancelled item throws)
HDR-Development/HewDraw-Remix pull request #630
Opened 2022-06-03 16:02 UTC by JoaoAlmeida20

Changes two important aspects of AGT:
1. You can no longer cancel an airdodge at any time into the item throw. It's now a 3-frame window at the very start of airdodge, frames 1-3.
2. If you cancel airdodge into item throw, you don't burn your use of airdodge, and can use it again without having to land.

Additionally this PR also increases Toon Link's bomb throw speed multiplier, it was very low to facilitate bomb regrabs, but with this mechanic it allowed him to chain AGTs for free and fly around. Since the throw speed was also too low for when you wanted to actually throw the bomb anyway, it was agreed to increase it after some discussion, instead of reworking AGTs with some sort of staling mechanic.

Discussion: https://discord.com/channels/659964948365049887/950977159088975883/982277295416967168
Toon Link flight before adjusting his throw strength: https://streamable.com/3xhwja
Regular example showing off the new possibilities and limitations: https://streamable.com/cf4jnq

Resolves #615

2022-06-04 09:44 UTC, Riah321 commented
It works as intended! Really happy with how Young Link's recovery is effected. If your character has a zair and you miss the AGT you'll get that instead which is pretty punishing if you don't want it. Love how it raises the skill floor and ceiling of AGTs.

Do keep in mind that it does open up for some high execution stalling techniques as link and toon link (though not infinite in toon link's case) in some matchups and on certain stages. Adding diminishing distance after a certain number of AGTs, or only allowing for a set amount per airtime would prevent these exploits. If implemented I recommend 3 AGTs before diminishing, or 5 before running out.

After preventing the stalling techniques it's good to go!

2022-06-04 17:16 UTC, techyCoder81 approved these changes
short and simple

2022-06-04 17:17 UTC, techyCoder81 requested changes
actually i just remembered that we wanted this to be changed so that it can only be done once per airtime, my b

2022-06-05 07:16 UTC, Riah321 commented
The limit to one per airtime has accidentally made it 0 per airtime. This is rather unfortunate.


Jokes aside you can only get zair and in frame by frame you get nothing.

2022-06-05 23:07 UTC, Riah321 commented
It works! I was going to complain about the AGT scaling but it's exactly where it needs to be! Ship it as soon as you're able.
The link stalls are fixed without making it unusable for normal use. Hooray!

2022-06-06 12:37 UTC, techyCoder81 approved these changes, later dismissed
Lgtm, just need agt logic retested as well as a small quick check to make sure the other var resets still work (should be fine, logic is sound)

2022-06-06 23:49 UTC, jobrien97 commented on fighters/common/src/opff/var_resets.rs
> +    let damage_statuses = &[*FIGHTER_STATUS_KIND_DEAD,
This array should be death_statuses

2022-06-06 23:49 UTC, jobrien97 commented on fighters/common/src/opff/var_resets.rs
> +    let death_statuses = &[*FIGHTER_STATUS_KIND_DAMAGE,
This should be damage_statuses

2022-06-07 03:23 UTC, Riah321 commented
It works! The tapering of AGTs is in a great spot, you don't get it back if you mash throw after an airdodge completes, and tink cannot fly. Ship it!

2022-06-07 03:50 UTC, Riah321 commented
Crashes on the character select screen for multiplayer. This could be a nightly issue, however.

2022-06-08 20:49 UTC, techyCoder81 approved these changes

2022-06-08 20:49 UTC, merged