metaquick fx and remove lots of println
HDR-Development/HewDraw-Remix pull request #682
Opened 2022-06-15 19:21 UTC by blu-dev

https://cdn.discordapp.com/attachments/950979381654855701/986704676361764914/2022-06-15_11-51-22.mp4

2022-06-15 20:01 UTC, techyCoder81 requested changes
overall good besides some preferred changes

2022-06-15 20:01 UTC, techyCoder81 commented on fighters/metaknight/src/meta_quick.rs
> +        if fighter.is_cat_flag(Cat2::AppealLw) {
any particular reason why this is AppealLw instead of AppealAll like before?

2022-06-15 20:01 UTC, techyCoder81 commented on fighters/metaknight/src/meta_quick.rs
> +        // return;
honestly at this point all of this commented stuff should just be removed, theres no reason to keep it. If its an issue we would just revert, and if not, its just clutter. So imo just delete it (at least once tested).

2022-06-15 20:01 UTC, techyCoder81 commented on fighters/metaknight/src/meta_quick.rs
> +pub unsafe extern "C" fn metaquick_summon_pre(fighter: &mut L2CFighterCommon) -> L2CValue {
my only question here is, do we want to restructure this to have this structure instead, to be a little more organized:
```
/meta_quick/
    /status.rs
    /acmd.rs
    /opff.rs

2022-06-15 23:00 UTC, blu-dev commented on fighters/metaknight/src/meta_quick.rs
> +        if fighter.is_cat_flag(Cat2::AppealLw) {
1. the down taunt animation is close enough to the animation that we play for metaquick
2. by mapping all taunt buttons, you are removing the ability to footstool in the air without using the footstool button

2022-06-15 23:01 UTC, blu-dev commented on fighters/metaknight/src/meta_quick.rs
> +        // return;
yep I just forgot to remove them, will do so

2022-06-15 23:01 UTC, blu-dev commented on fighters/metaknight/src/meta_quick.rs
> +pub unsafe extern "C" fn metaquick_summon_pre(fighter: &mut L2CFighterCommon) -> L2CValue {
I don't think we need to change the structure. The status code is small enough that putting it in it's own file would be wasteful imo. The ACMD is also really small so I don't think it's important enough to do that. The bulk of the speed setting and management logic is in OPFF anyways.

2022-06-16 01:10 UTC, techyCoder81 commented
ready for final testing

2022-06-16 05:22 UTC, Riah321 commented
Tested and works! Fair trains aren't free either, if that was a concern.

2022-06-16 15:10 UTC, techyCoder81 approved these changes

2022-06-16 15:10 UTC, merged