Falco changes
HDR-Development/HewDraw-Remix pull request #725
Opened 2022-06-22 22:10 UTC by TeamPearson

2022-06-23 14:28 UTC, jobrien97 requested changes

2022-06-23 14:28 UTC, jobrien97 commented on fighters/falco/src/acmd/specials.rs
> +        println!("RUSH DEGREE: {}", WorkModule::get_float(fighter.boma(), *FIGHTER_FALCO_FIRE_STATUS_WORK_ID_FLOAT_TO_RUSH_DEGREE));
Remove println

2022-06-23 14:28 UTC, jobrien97 commented on fighters/falco/src/acmd/specials.rs
> +        }
This will make him unable to grab ledge during upB startup, when we implement it

2022-06-23 16:34 UTC, techyCoder81 commented on fighters/falco/src/acmd/specials.rs
> +        println!("RUSH DEGREE: {}", WorkModule::get_float(fighter.boma(), *FIGHTER_FALCO_FIRE_STATUS_WORK_ID_FLOAT_TO_RUSH_DEGREE));
this is still a draft PR lol

2022-06-23 19:17 UTC, TeamPearson commented on fighters/falco/src/acmd/specials.rs
> +        }
removed in favor of a param edit

2022-06-24 10:20 UTC, yoonikoo commented
Changes are solid. Can gladly say that Falco is now more consistent.

2022-06-24 12:05 UTC, Riah321 commented
tired but it's good to go. ship it.

2022-06-24 15:52 UTC, jobrien97 requested changes

2022-06-24 15:52 UTC, jobrien97 commented on fighters/falco/src/acmd/specials.rs
> +        }
doesn't need to be here

2022-06-24 15:52 UTC, jobrien97 commented on fighters/falco/src/acmd/specials.rs
> +            FT_MOTION_RATE(fighter, 5.0/(4.0-1.0));
extra indentation?

2022-06-24 15:52 UTC, jobrien97 commented on fighters/falco/src/acmd/specials.rs
> +       ("RUSH DEGREE: {}", WorkModule::get_float(fighter.boma(), *FIGHTER_FALCO_FIRE_STATUS_WORK_ID_FLOAT_TO_RUSH_DEGREE));
remove println

2022-06-25 05:51 UTC, TeamPearson commented on fighters/falco/src/acmd/specials.rs
> +        }
removed

2022-06-25 05:51 UTC, TeamPearson commented on fighters/falco/src/acmd/specials.rs
> +            FT_MOTION_RATE(fighter, 5.0/(4.0-1.0));
removed

2022-06-25 05:51 UTC, TeamPearson commented on fighters/falco/src/acmd/specials.rs
> +       ("RUSH DEGREE: {}", WorkModule::get_float(fighter.boma(), *FIGHTER_FALCO_FIRE_STATUS_WORK_ID_FLOAT_TO_RUSH_DEGREE));
removed

2022-06-26 02:09 UTC, techyCoder81 approved these changes

2022-06-26 02:09 UTC, merged