Added a lot - New Lucas just Dropped
HDR-Development/HewDraw-Remix pull request #751
Opened 2022-06-28 01:40 UTC by HisashiASM

+ Added Offence Up
+ Added Windboxes for OU on frame 14
+ Offence Up charges for 3 seconds - Retains charge when hit out or special button is released
+ Offense Up is lost when whiffing Smashes, Death, Reset or OU Burst
+ Added OU Burst and OU Burst Freeze
+ Added new Smashes for Offence Up
+ Added Tiltable Forward Smash
+ UTaunt goes into Slip if held
+ Muted voicelines for SSpecial and NSpecial
* DAir readjusted to fit new design
* Shortened DSmash hits from 3 to 1
* Shortened USmash (uncharged) times to end hitboxes on f43
* Fixed audio bug on Jab 1-2-3

2022-07-01 08:32 UTC, Riah321 commented
New mechanics feel really good. Offense up seems fair in it's current state.
Down air feels really jank but probably skill issue.

2022-07-07 01:19 UTC, jobrien97 commented
Please edit AttackLw4's `expression` ACMD script to account for the new single-hit functionality. Controller still rumbles 3 times.

2022-07-12 14:09 UTC, jobrien97 requested changes

2022-07-12 14:09 UTC, jobrien97 commented on fighters/lucas/src/acmd/specials.rs
> +                EFFECT_FLW_POS(fighter, Hash40::new("lucas_pkfr_hold"), Hash40::new("top"), 0, sv_math::rand(hash40("fighter"), 4) as i32 + 12, sv_math::rand(hash40("fighter"), 4) as i32 - 2, 0, 0, 0
You can use the `emit` bone to make an effect spawn randomly on a character's body

2022-07-12 15:16 UTC, jobrien97 commented on fighters/lucas/src/opff.rs
> +        }
This should be moved to SPECIAL_N's pre status, using set_status_kind_interrupt if the flag is on. Else, call original.
Doing this in opff causes the change_status_request_from_script to run on frame 2 of SPECIAL_N, as status_kind isn't updated until then

2022-07-12 15:17 UTC, jobrien97 commented on fighters/lucas/src/status.rs
> +
pls comment `// FIGHTER_LUCAS_STATUS_KIND_SPECIAL_N_HOLD //` here, to keep consistent with our status script organization

2022-07-12 18:11 UTC, jobrien97 approved these changes
lgtm :D

2022-07-13 14:58 UTC, merged