Rosalina Teleport downb
HDR-Development/HewDraw-Remix pull request #785
Opened 2022-07-03 21:25 UTC by chrispo-git

Rosalina downb now acts as a teleport, swapping her and Luma's position.
Frames 17-24 - invulnerable (teleporting)
Frame 38 - Actionable

Rosalina cannot use downb for 300 frames (5 seconds) afterwards, and her being able to use it again is indicated by a flash on her hands and on the HUD

https://user-images.githubusercontent.com/69305550/177057739-f0bee2e4-5758-48f0-8e09-984b94f8e265.mp4

2022-07-04 01:24 UTC, WuBoytH commented on fighters/rosetta/src/opff.rs
> +#[smashline::weapon_frame_callback]
Weapons can have their own specific fighter frames, you can change the attribute to this `#[weapon_frame( agent = WEAPON_KIND_ROSETTA_TICO )]`

2022-07-04 01:26 UTC, WuBoytH requested changes
Look at my comment about Luma's OPFF. Other than that, it should need playtesting (and a second opinion from someone else) for further adjustments before approval.

2022-07-07 00:59 UTC, jobrien97 commented
Please change the indicator when teleport is recharged to our common gimmick flash effect found in common/src/opff/gimmick.rs

2022-07-12 03:22 UTC, WuBoytH commented on fighters/rosetta/src/opff.rs
> +					VarModule::set_int(fighter.battle_object, vars::rosetta::instance::COOLDOWN,  VarModule::get_int(fighter.battle_object, vars::rosetta::instance::COOLDOWN)-1);
you can just do `VarModule::dec_int(fighter.battle_object, vars::rosetta::instance::COOLDOWN);` to decrement this var by 1.

2022-07-12 03:24 UTC, WuBoytH commented on fighters/rosetta/src/opff.rs
> +				VarModule::set_int(fighter.battle_object, vars::rosetta::instance::TICO_RAYCAST,
I would appreciate that you don't nest VarModule calls for readability purposes.
`let rosa_x = ...;`, `let tico_x = ...;`, etc.

2022-07-12 03:28 UTC, WuBoytH requested changes
Just a few smaller, organizational changes are needed before we can merge this in.

2022-07-18 14:43 UTC, WuBoytH approved these changes
LGTM

2022-07-18 16:12 UTC, merged