Turnaround special/B-reverse reimplementation
HDR-Development/HewDraw-Remix pull request #899
Opened 2022-08-04 04:47 UTC by jobrien97

Turnaround special/B-reverse now uses vanilla logic, rather than our hacky workaround method.

Fixes #890

2022-08-04 04:56 UTC, WuBoytH approved these changes
This will remove "tech" born from the old special-reverse implementation, like Falcon's "Wavekick". Expect backlash (which I completely approve of).

2022-08-04 04:59 UTC, WuBoytH requested changes
Ah sorry I need to make an addendum
since the status_attr field is a bitmask, you need to make sure that
1. You add the value of *FIGHTER_STATUS_ATTR_START_TURN to the bitmask, instead of setting the bitmask itself.
2. You check if the bitmask *already contains* FIGHTER_STATUS_ATTR_START_TURN before adding to it.

2022-08-04 05:54 UTC, WuBoytH approved these changes
Free to merge once someone else tests it in-game

2022-08-08 20:16 UTC, MadVillainLordQ commented
Tested in game, LGTM

2022-08-08 21:03 UTC, merged