Resolve Tilt button not triggering AB Smash
HDR-Development/HewDraw-Remix pull request #915
Opened 2022-08-08 15:14 UTC by techyCoder81

Currently, tilt button cannot be used to trigger AB smash. This is because we clear all smash inputs if a TiltAttack input is found.

Instead, this change makes it so that we only clear smash inputs if the player has not pressed an *explicit* smash button. For example, smash stick and AB Smash are both internally register as a Smash button. However, a manually input smash attack using a regular Attack button does not register a Smash button prior to cat flag mappings. Therefore this operation should be safe.

Please test this PR to ensure that the change works as expected.

2022-08-08 21:08 UTC, WuBoytH approved these changes, later dismissed

2022-08-08 23:35 UTC, MadVillainLordQ commented
Unfortunately, this was not able to resolve the issue. Pressing A+B with tilt button enabled results in a special attack.

2022-08-09 01:26 UTC, jobrien97 requested changes
does not solve the issue

2022-08-10 06:51 UTC, Riah321 commented
It did not, in fact, fix the issue.

2022-10-10 02:30 UTC, closed without merging