Shulk adjustments
HDR-Development/HewDraw-Remix pull request #994
Opened 2022-08-31 00:40 UTC by Riah321

WIP, and extremely jank as I wrote this on a plane while only going off memory and a prewritten .txt file. Mostly so that hypothesis has something to chew on while I wait to get home.
Atm mostly frame data and damage adjustments, but there's a couple of angle adjustments and hitbox size/placement adjustments as well.

2022-09-10 17:46 UTC, IRBDaUrges commented
Love these Changes :)

2022-09-11 01:57 UTC, Riah321 commented
Shulk is officially finished!

2022-09-11 03:00 UTC, WuBoytH requested changes
Looks good, but I left one comment on something that should be changed for readability.

2022-09-11 03:00 UTC, WuBoytH commented on fighters/shulk/src/acmd/ground.rs
> +    wait(lua_state, 1.0);
You got rid of hitboxes 1 and 2, but didn't remove the AttackModule::clear calls for those hitboxes.

2022-09-11 06:54 UTC, Riah321 commented on fighters/shulk/src/acmd/ground.rs
> +    wait(lua_state, 1.0);
o7

2022-09-11 13:36 UTC, WuBoytH approved these changes, later dismissed

2022-09-29 21:10 UTC, SkewedAskew requested changes, later dismissed
Remove the Toon Link files and param changes, otherwise lgtm

2022-10-16 06:53 UTC, SkewedAskew commented
Changelog: [Shulk_changes.txt](https://github.com/HDR-Development/HewDraw-Remix/files/9793778/Shulk_changes.txt)

Hitbox Comparisons: soonTM

2022-10-16 16:25 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 16:38 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 16:51 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 17:16 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 17:21 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 17:29 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 17:45 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 18:33 UTC, hdr-balance-backroom commented
APPROVED

2022-10-16 19:25 UTC, hdr-balance-backroom approved these changes

2022-10-16 19:44 UTC, techyCoder81 approved these changes
lgtm

2022-10-16 19:45 UTC, merged